export const styles = {
  container: {
    fontFamily: '"Helvetica Neue", Arial, sans-serif',
    maxWidth: '400px',
    margin: '50px auto',
    padding: '30px',
    borderRadius: '16px',
    boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
    textAlign: 'center',
    backgroundColor: '#ffffff',
  },
  header: { color: '#14233c', marginBottom: '20px' },
  input: {
    padding: '12px',
    fontSize: '20px',
    width: '100%',
    marginBottom: '15px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    textAlign: 'center',
    letterSpacing: '4px',
    boxSizing: 'border-box',
  },
  button: {
    padding: '14px 24px',
    fontSize: '16px',
    backgroundColor: '#ff4d4d', // Monzo Hot Coral
    color: 'white',
    border: 'none',
    borderRadius: '30px',
    cursor: 'pointer',
    width: '100%',
    fontWeight: 'bold',
  },
  secondaryButton: {
    marginTop: '15px',
    background: 'none',
    border: 'none',
    color: '#1a73e8',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
  },
  spinner: {
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #ff4d4d',
    borderRadius: '50%',
    width: '30px',
    height: '30px',
    margin: '20px auto',
    // Note: CSS animation requires index.css addition (see below)
  },
  error: { color: '#d93025', fontSize: '14px', marginTop: '10px' },
  notification: {
    backgroundColor: '#e8f0fe',
    padding: '12px',
    borderRadius: '8px',
    fontSize: '13px',
    color: '#1a73e8',
    marginBottom: '20px',
  },
};